-keep class com.mjh.shizukufix.XposedLoader { *; }
-keep class com.mjh.shizukufix.hooks.** { *; }
-keep class com.mjh.shizukufix.utils.** { *; }
-keep class com.mjh.shizukufix.models.** { *; }
-keep class de.robv.android.xposed.** { *; }
-dontwarn de.robv.android.xposed.**
-dontwarn rikka.shizuku.**
-dontwarn moe.shizuku.**
-keepclassmembers class com.mjh.shizukufix.models.** { *; }
-keepattributes *Annotation*,Signature,EnclosingMethod
