package com.stepmod.pro.utils

import java.lang.reflect.Method

/**
 * Shizuku 联动助手（Root 版）
 *
 * 功能：
 *  1. 检测 Shizuku 服务是否可用
 *  2. 通过反射调用 Shizuku.newProcess 执行系统级 Shell 命令
 *     - 写 /sys/class/sensors/step_counter/value（系统级步数节点）
 *     - am broadcast 广播步数更新
 *     - 写 /proc/step_counter 内核节点
 *     - settings put 修改系统设置
 *
 * 硬性限制：
 *  - 系统级 Hook 必须先检查 isShizukuAvailable()
 *  - 写 /sys /proc 需要 root 级别 Shizuku 授权（adb 级可能权限不足）
 *  - 所有调用通过 try-catch 保护，失败不影响其他 Hook
 */
object ShizukuHelper {

    private const val TAG = "ShizukuHelper"
    private var shizukuAvailable: Boolean? = null

    /** 检查 Shizuku 是否可用 */
    fun isShizukuAvailable(): Boolean {
        if (shizukuAvailable != null) return shizukuAvailable!!
        shizukuAvailable = try {
            val cls = Class.forName("rikka.shizuku.Shizuku")
            val method: Method = cls.getMethod("pingBinder")
            val result = method.invoke(null) as? Boolean ?: false
            LogX.d("Shizuku状态: $result")
            result
        } catch (e: Exception) {
            LogX.w("Shizuku不可用或未安装: ${e.message}")
            false
        }
        return shizukuAvailable!!
    }

    /**
     * 通过 Shizuku 执行 shell 命令
     * @return 命令输出（stdout），失败返回 null
     */
    fun execShell(command: String): String? {
        return try {
            if (!isShizukuAvailable()) return null
            val shizukuCls = Class.forName("rikka.shizuku.Shizuku")
            val newProcessMethod = shizukuCls.getMethod(
                "newProcess",
                Array<String>::class.java,
                Array<String>::class.java,
                String::class.java
            )
            val process = newProcessMethod.invoke(
                null,
                arrayOf("sh", "-c", command),
                null,
                null
            ) ?: return null

            val isMethod = process.javaClass.getMethod("getInputStream")
            val isStr = isMethod.invoke(process) as? java.io.InputStream
            val out = isStr?.bufferedReader()?.readText()

            try {
                val waitFor = process.javaClass.getMethod("waitFor")
                waitFor.invoke(process)
            } catch (e: Throwable) { LogX.w("异常: ${e.message}") }

            out
        } catch (e: Exception) {
            LogX.e("Shizuku Shell执行异常: $command", e)
            null
        }
    }

    /** 仅执行不关心输出，返回是否执行成功（未抛异常且 Shizuku 可用） */
    fun execShellSilent(command: String): Boolean {
        return try {
            if (!isShizukuAvailable()) return false
            execShell(command) != null
        } catch (_: Throwable) {
            false
        }
    }

    /**
     * 通过 Shizuku 写入文件（需 root 级别）
     * 用于写 /sys/class/sensors/step_counter/value、/proc/... 等
     */
    fun writeFile(path: String, content: String): Boolean {
        return try {
            if (!isShizukuAvailable()) return false
            val escaped = content.replace("'", "'\\''")
            execShell("echo '$escaped' > $path") != null
        } catch (e: Exception) {
            LogX.e("Shizuku写入文件异常: $path", e)
            false
        }
    }

    fun readFile(path: String): String? {
        return try {
            if (!isShizukuAvailable()) return null
            execShell("cat $path 2>/dev/null")
        } catch (_: Throwable) { null }
    }

    fun reset() {
        shizukuAvailable = null
    }

    /**
     * 通过 Shizuku 执行 SQLite 命令
     * @param dbPath 数据库文件路径
     * @param sql SQL 语句
     * @return 命令输出，失败返回 null
     */
    fun execSqlite(dbPath: String, sql: String): String? {
        return try {
            if (!isShizukuAvailable()) return null
            execShell("sqlite3 '$dbPath' \"$sql\"")
        } catch (e: Throwable) {
            LogX.w("execSqlite 异常: ${e.message}")
            null
        }
    }

    /**
     * 通过 Shizuku 创建 Magisk overlay 模块目录
     * 用于持久化修改 /system 下的属性/配置（重启后仍生效）
     * @param moduleId Magisk 模块 ID
     * @return 是否创建成功
     */
    fun createMagiskOverlay(moduleId: String): Boolean {
        if (!isShizukuAvailable()) return false
        val base = "/data/adb/modules/$moduleId"
        return try {
            execShellSilent("mkdir -p $base/system") &&
            execShellSilent("echo 'id=$moduleId' > $base/module.prop") &&
            execShellSilent("echo 'name=LSP-Model $moduleId' >> $base/module.prop") &&
            execShellSilent("echo 'version=v1.0.11' >> $base/module.prop") &&
            execShellSilent("echo 'author=MJH' >> $base/module.prop") &&
            execShellSilent("echo 'description=Auto-generated by LSP-Model' >> $base/module.prop")
        } catch (e: Throwable) {
            LogX.w("createMagiskOverlay 异常: ${e.message}")
            false
        }
    }


    /** 通过 Shizuku 写 Magisk overlay 文件 */
    fun writeMagiskOverlay(moduleId: String, relPath: String, content: String): Boolean {
        val base = "/data/adb/modules/" + moduleId
        val fullPath = base + "/system/" + relPath
        val dir = fullPath.substring(0, fullPath.lastIndexOf('/'))
        execShellSilent("mkdir -p " + dir)
        return writeFile(fullPath, content)
    }

    fun release() {
        shizukuAvailable = null
    }
}
