package com.batteryopt.pro.utils

/**
 * Shizuku 联动助手
 *
 * 功能：
 *  1. 检测 Shizuku 服务是否可用
 *  2. 通过反射调用 Shizuku API 执行系统命令（dumpsys/settings/am/setprop 等）
 *
 * 硬性限制：
 *  - LSPatch 本地模式下 Shizuku 未必运行，所有调用通过反射 + try-catch 保护
 *  - am force-stop / dumpsys deviceidle / 写 sysfs 节点等系统级操作均需 Shizuku 授权
 *
 * 使用前必须：
 *  1. 安装 Shizuku App
 *  2. 通过无线调试或 ADB 激活 Shizuku
 *  3. 在 Shizuku 中授权本模块
 */
object ShizukuHelper {

    private var shizukuAvailable: Boolean? = null

    /** 检查 Shizuku 是否可用 */
    fun isShizukuAvailable(): Boolean {
        if (shizukuAvailable != null) return shizukuAvailable!!
        shizukuAvailable = try {
            val cls = Class.forName("rikka.shizuku.Shizuku")
            val method = cls.getMethod("pingBinder")
            val result = method.invoke(null) as? Boolean ?: false
            LogX.d("Shizuku 状态: $result")
            result
        } catch (e: Exception) {
            LogX.w("Shizuku 不可用或未安装: ${e.message}")
            false
        }
        return shizukuAvailable!!
    }

    /**
     * 通过 Shizuku 执行 Shell 命令
     * 用于：dumpsys deviceidle / am force-stop / settings put global / 写 sysfs 节点等
     *
     * @param command Shell 命令
     * @return 命令输出（stdout），失败返回 null
     */
    fun execShell(command: String): String? {
        return try {
            if (!isShizukuAvailable()) {
                LogX.w("Shizuku 不可用，跳过命令: $command")
                return null
            }
            val shizukuCls = Class.forName("rikka.shizuku.Shizuku")
            val newProcessMethod = shizukuCls.getMethod(
                "newProcess",
                Array<String>::class.java,
                Array<String>::class.java,
                String::class.java
            )
            val process = newProcessMethod.invoke(
                null,
                arrayOf("sh", "-c", command),
                null,
                null
            ) ?: return null
            val inputStream = process.javaClass.getMethod("getInputStream").invoke(process)
                as? java.io.InputStream
            val stdout = inputStream?.bufferedReader()?.readText()
            try { process.javaClass.getMethod("waitFor").invoke(process) } catch (e: Exception) { LogX.w("异常: ${e.message}") }
            stdout
        } catch (e: Exception) {
            LogX.e("Shizuku Shell 执行异常: $command", e)
            null
        }
    }

    /** 通过 Shizuku 设置系统属性 */
    fun setSystemProperty(key: String, value: String): Boolean {
        val result = execShell("setprop $key $value")
        return result != null
    }

    /** 仅执行不关心输出，返回是否执行成功（未抛异常且 Shizuku 可用） */
    fun execShellSilent(command: String): Boolean {
        return try {
            if (!isShizukuAvailable()) return false
            execShell(command) != null
        } catch (_: Throwable) {
            false
        }
    }

    /**
     * 通过 Shizuku 执行 SQLite 命令
     * @param dbPath 数据库文件路径
     * @param sql SQL 语句
     * @return 命令输出，失败返回 null
     */
    fun execSqlite(dbPath: String, sql: String): String? {
        return try {
            if (!isShizukuAvailable()) return null
            execShell("sqlite3 '$dbPath' \"$sql\"")
        } catch (e: Throwable) {
            LogX.w("execSqlite 异常: ${e.message}")
            null
        }
    }

    /**
     * 通过 Shizuku 创建 Magisk overlay 模块目录
     * 用于持久化修改 /system 下的属性/配置（重启后仍生效）
     * @param moduleId Magisk 模块 ID
     * @return 是否创建成功
     */
    fun createMagiskOverlay(moduleId: String): Boolean {
        if (!isShizukuAvailable()) return false
        val base = "/data/adb/modules/$moduleId"
        return try {
            execShellSilent("mkdir -p $base/system") &&
            execShellSilent("echo 'id=$moduleId' > $base/module.prop") &&
            execShellSilent("echo 'name=LSP-Model $moduleId' >> $base/module.prop") &&
            execShellSilent("echo 'version=v1.0.11' >> $base/module.prop") &&
            execShellSilent("echo 'author=MJH' >> $base/module.prop") &&
            execShellSilent("echo 'description=Auto-generated by LSP-Model' >> $base/module.prop")
        } catch (e: Throwable) {
            LogX.w("createMagiskOverlay 异常: ${e.message}")
            false
        }
    }

    /** 释放资源 */
    fun release() {
        shizukuAvailable = null
    }
}
